document.writeln("<!--ÀÊ∆¡“∆∂ØÕº∆¨¥˙¬Î-->");
document.writeln("<style type=\"text\/css\">");
document.writeln("<!-- ");
document.writeln("body{font-size=9pt}");
document.writeln("TH{FONT-SIZE: 9pt}");
document.writeln("TD{ FONT-SIZE: 9pt}");
document.writeln("#floater {");
document.writeln("position: absolute;");
document.writeln("left: 874px;");
document.writeln("top: 600;");
document.writeln("width: 125;");
document.writeln("visibility: visible;");
document.writeln("z-index: 10;");
document.writeln("}");
document.writeln("-->");
document.writeln("<\/style>");

document.writeln("<script>");
document.writeln("var online= new Array();");
document.writeln("if (!document.layers)");
document.writeln("document.write(\'<div id=\"divStayTopLeft\" style=\"position:absolute\">\')");
document.writeln("<\/script>");
document.writeln("<!--ÀÊ∆¡“∆∂ØÕº∆¨¥˙¬Î-->");
document.writeln("");
document.writeln("");
document.writeln("<div ID=\"floater\" style=\"right: 2px; top: 153px; width: 48px; height: 48px\" style=\"display:none\"> ");
document.writeln("");
document.writeln("<TABLE cellSpacing=0 cellPadding=0 width=100 align=center border=0 id=\"table2\">");
document.writeln("  <TBODY>");
document.writeln("  <TR>");
document.writeln("    <TD>");
document.writeln("	<IMG height=55 ");
document.writeln("      src=\"/images\/up_001.gif\" ");
document.writeln("      width=118 useMap=#Map border=0><map name=\"Map\" id=\"Map\"><area shape=\"rect\" coords=\93,1,115,19\ href=\"javascript:void(0);\" onclick=\"adnone();\" /></map><\/TD><\/TR><\/TBODY><\/TABLE>");
document.writeln("");
document.writeln("<DIV id=tracq1>");
document.writeln("");
document.writeln("<TABLE cellSpacing=0 cellPadding=0 width=100 align=center border=0 id=\"table3\" >");
document.writeln("  <TBODY>");
document.writeln("  <TR>");
document.writeln("    <TD class=cpx12hei vAlign=center align=middle width=118 ");
document.writeln("    background=\"/images\/mid001.gif\" ");
document.writeln("    height=80>");

document.writeln("");
document.writeln("      <TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0 id=\"table5\">");
document.writeln("        <TBODY>");
document.writeln("        <TR>");
document.writeln("          <TD height=5>");
document.writeln("<SPAN id=ad_01>…Ÿµ»‘ÿ»Î÷–...<\/SPAN>");
document.writeln("");
document.writeln("<\/TD><\/TR><\/TBODY><\/TABLE>");
document.writeln("     ");
document.writeln("");
document.writeln("    <\/TD><\/TR>");
document.writeln("  <TR>");
document.writeln("    <TD>");
document.writeln("<IMG height=21 ");
document.writeln("      src=\"/images\/bot_001.gif\" ");
document.writeln("      width=118 align=center border=0><\/TD><\/TR><\/TBODY><\/TABLE><\/TD><\/TR><\/TBODY><\/TABLE><\/DIV><\/DIV><\/DIV><\/DIV>");
document.writeln("<p> ");
